### ISSUE TITLE
Some video playback corrupted on AMD GPUs

### ISSUE THREAD

**Issue by lucascenir** [cassidyjames/ephemeral#101]
Hello, I am using Ephemeral as my main web browser and I am having some troubles with watching YouTube videos, the video fully loads and even reproduces the content, the audio works however the video display is a mess, the colours aren't showed properly, creating an effect like datamosh
![captura de tela de 2019-02-09 14 57 26](https://user-images.githubusercontent.com/14957594/52523818-96423900-2c7c-11e9-826d-8e3dc356ffd3.png)
Besides that, it is an amazing browser, good job! <3

**Comment by cassidyjames** [comment]
@lucascenir I've seen this issue in other WebKit-based browsers depending on the video drivers in use. What GPU/drivers are you using?

**Comment by lucascenir** [comment]
I run `lshw -c video` and the output is:
```
  *-display                 
       description: VGA compatible controller
       product: Mullins [Radeon R2 Graphics]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical ID: 1
       bus info: pci@0000:00:01.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:35 memória:e0000000-efffffff memória:f0000000-f07fffff porta de E/S:3000(tamanho=256) memória:f0c00000-f0c3ffff memória:c0000-dffff

```

**Comment by hannesschulze** [comment]
Same problem on my RX 580, although this is not only in Ephemeral but also in Videos and Epiphany. This is probably related to this issue: https://github.com/elementary/os-patches/issues/46

**Comment by cassidyjames** [comment]
Closing since it's not something I can address.
