### ISSUE TITLE
Incorrect TLD for joinmastodon

### ISSUE THREAD

**Issue by Akzel94** [cassidyjames/ephemeral#109]
With the new popular sites feature, the Mastodon homepage is suggested as joinmastodon.com, when it should be joinmastodon.org

![joinmastodon.com](https://spee.ch/1c14f56d21a7410a88584c702430b7f988e15c72/ephemeral-joinmastodon-com-2019-02-21.png)

![joinmastodon.org](https://spee.ch/579ed70f9740443e04ce2f63e5432071cbf9d7c0/ephemeral-joinmastodon-org-2019-02-21.png)

**Comment by cassidyjames** [comment]
@Akzel94 well that's embarrassing. Thanks!
