### ISSUE TITLE
Allow custom stylesheet use on non-native os's

### ISSUE THREAD

**Issue by worldofpeace** [cassidyjames/ephemeral#122]
It works fine if the os isn't elementary but we're still running pantheon and using their stylesheet.
So maybe just drop the restriction on the os id being `elementary`?

Noticed this when I was reviewing this package being added to [NixOS](https://github.com/NixOS/nixpkgs/pull/57246).

Here's a screenshot of it there but without the os restriction
![Screenshot from 2019-03-10 19 21 55](https://user-images.githubusercontent.com/28888242/54093057-56f62d80-438b-11e9-991b-8d0ca6aa0768.png)

Looks fine as we can see.

**Comment by cassidyjames** [comment]
@worldofpeace in this case, Ephemeral is not running on elementary OS, and I cannot guarantee the experience. Just because a stylesheet exists that's called "elementary" does not guarantee the stylesheet version that supports the Palette API. It also means that I can't know if AppCenter is installed and, as seen in your screenshot, Ephemeral would incorrectly direct users to open AppCenter to purchase the app.

I'm inclined to close this unless you can convince me otherwise. :smile:

**Comment by worldofpeace** [comment]
> I'm inclined to close this unless you can convince me otherwise. smile

Inclined isn't the same as "closing promptly". So I would have appreciated you at least waiting for me to respond. Especially when you offered me to convince you.

However I understand that you'd like to spend your time guaranteeing the best experience for your users, and anything that can be seen as interference could be a deterrent to this. That's a fruitful mindset

So I won't waste your time.

**Comment by cassidyjames** [comment]
@worldofpeace issues can be reopened, no state is permanent :wink:

**Comment by cassidyjames** [comment]
@worldofpeace if you're still interested, more recent versions of Ephemeral have separated out the concepts of "native" and "elementary stylesheet". I apply the elementary styling if you're using an elementary stylesheet, regardless of whether it's running on elementary OS. Hopefully this helps!

https://github.com/cassidyjames/ephemeral/blob/5be06875e9f9792ea1ae5ae27c2873a7103be177/src/Application.vala#L124-L155

https://github.com/cassidyjames/ephemeral/blob/5be06875e9f9792ea1ae5ae27c2873a7103be177/src/Application.vala#L82-L92

**Comment by worldofpeace** [comment]
@cassidyjames I believe I did notice this and I was happily surprised. Thanks :heart:
