### ISSUE TITLE
Windows edition in the works? Recommendations?

### ISSUE THREAD

**Issue by CyberSecGuy** [cassidyjames/ephemeral#143]
Hey there, I really like this browser and the thought of it, but for work and school purposes I require a Windows based OS. Are there any plans to bring this over to Windows? If not, do you have any recommendations for alternatives?

Thanks! Hopefully I can join the linux squad on a full time basis soon!

**Comment by TingPing** [comment]
WebKitGTK does not support Windows so this isn't even possible.

**Comment by cassidyjames** [comment]
@CyberSecGuy I don't have plans to make a Windows version. I've heard of people configuring an alternate browser to behave similarly to Ephemeral, and then using that as their default. I don't have experience with that, though.
