### ISSUE TITLE
Automatic conversion from Punycode

### ISSUE THREAD

**Issue by jlnr** [cassidyjames/ephemeral#152]
If I open https://www.xn--heldenldchen-mcb.de/ in Epiphany (link via YouTube), it is automatically converted to heldenlädchen.de, not so in Ephemeral.

**Comment by TingPing** [comment]
Arguably this is just a more secure default behavior.

**Comment by cassidyjames** [comment]
There is an algorithm to attempt to allow intended punycode domains through (showing the domain as a user would expect) while also being transparent about potentially-malicious domains: https://wiki.mozilla.org/IDN_Display_Algorithm#Algorithm

I could see that being a good compromise.

**Comment by cassidyjames** [comment]
It looks like WebKit has a built-in now that has a security check (similar to Mozilla). Not sure how to use it from Vala on Juno, though, as the bindings seem out of date. https://webkitgtk.org/reference/webkit2gtk/stable/webkit2gtk-4.0-WebKitURIUtilities.html#webkit-uri-for-display
