### ISSUE TITLE
Closing one window sometimes closes others along with it

### ISSUE THREAD

**Issue by jlnr** [cassidyjames/ephemeral#161]
1. Open a website in Ephemeral.
2. Middle-click any link to open a second window.
3. Close the original window using the X button.

Expected: Only the first window is closed.

Actual: Both windows are closed.

**Comment by cassidyjames** [comment]
Yikes, thanks for catching that! I'll look into it.

**Comment by cassidyjames** [comment]
This looks like it was introduced with the changes in #156, as I can't reproduce it in the commit immediately before it.
