### ISSUE TITLE
Ctrl+W behaves differently with one and several windows

### ISSUE THREAD

**Issue by jlnr** [cassidyjames/ephemeral#162]
If I only have one Ephemeral window, Ctrl+W closes the window/app.

But if I have several open windows and close one of them using Ctrl+W, a new window pops up in the middle of the screen.

**Comment by cassidyjames** [comment]
Hm, Ctrl+W was intended to fire the "Erase Browsing History" action, which closes the current window and reopens a new one, like the multi-window behavior. So it seems the single-window behavior here is actually "wrong" according to the design.

However, I can see how that behavior would be super annoying in multi-window sessions, and it actually predates Ephemeral's multi-window support. So I will probably just update it to close the window and _not_ open a new one...
