### ISSUE TITLE
Update user agent string from Safari 11?

### ISSUE THREAD

**Issue by DanGough** [cassidyjames/ephemeral#166]
Visiting Flathub.org, I get a pop up telling me my browser is out of date - it is using a script from https://browser-update.org that detects Ephemeral as Safari 11. No idea if 12 is now the latest, but it would be good to update the string so it stops receiving complaints. Especially as ElementaryOS are adopting Flatpak and lots of AppCenter apps are popping up on Flathub!

**Comment by cassidyjames** [comment]
I don't set a User Agent string at all, and just use the default from WebKit. User Agent sniffing is a terrible practice in the first place, and will almost always cause problems with smaller browsers like Ephemeral or Epiphany. I don't think it's my job to work around these site-specific issues (or lie in the User Agent string), so I'm inclined to close this.

I think opening an issue on Flathub to not use an external script to unnecessarily User Agent sniff is probably a more appropriate way to resolve this specific issue.

**Comment by TingPing** [comment]
I believe the next release of WebKitGTK also updated its default user agent which might solve this.
