### ISSUE TITLE
Buttons background gets corrupted

### ISSUE THREAD

**Issue by DanyGee** [cassidyjames/ephemeral#170]
Buttons background gets corrupted on my machine... 
![Screen record from 2019-08-31 10 06 10@2x](https://user-images.githubusercontent.com/26818551/64061173-0b546c00-cbd7-11e9-891b-e960993a3eb6.gif)

My hardware...
![image](https://user-images.githubusercontent.com/26818551/64061199-78680180-cbd7-11e9-9004-71139da179af.png)

**Comment by cassidyjames** [comment]
Closing this as it seems like an NVIDIA issue, and nothing I have control over personally.
