### ISSUE TITLE
Suggest to turn on “Close window when opening externally”

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/ephemeral#185]
I wonder if I could be really smart and detect if you frequently close the window after opening in another browser, and recommend you toggle that setting? :thinking: 🤯️

**Comment by zelikos** [comment]
Maybe you could have a check for how much time passes until the window is closed after opening externally; if the window is closed within a specific, short time period, add a count, and keep track of how many times it's happened while close-when-opening-externally is disabled.

If it hits a certain threshold, you could then prompt the user to toggle the setting.

**Comment by cassidyjames** [comment]
@zelikos thanks, that's exactly what I've done in #223. :smile:
