### ISSUE TITLE
"Close Window When Opening Externally" option not always accessible

### ISSUE THREAD

**Issue by jlnr** [cassidyjames/ephemeral#187]
When there is only one browser besides Ephemeral (typically Epiphany), there is no drop-down menu, and therefore no way to toggle the option to close the current Ephemeral window when opening it in an external browser.

The easiest fix is probably to always show the drop-down button.

**Comment by cassidyjames** [comment]
That would also probably clean up the BrowserButton logic a lot, which has gotten pretty unwieldy.
