### ISSUE TITLE
Only apply prefer dark to the headerbar

### ISSUE THREAD

**Issue by danrabbit** [cassidyjames/ephemeral#23]
Websites that use the default webkit controls typically don't look good inheriting the dark controls

**Comment by danrabbit** [comment]
Oh nevermind, I'm wrong. I guess this would only effect menus :man_shrugging:

**Comment by cassidyjames** [comment]
https://github.com/elementary/greeter/blob/7f36454d0a52328ef1dac9e8245e45326bb6276a/src/MainWindow.vala#L65

**Comment by cassidyjames** [comment]
I'm going to close this and the associated PR; I kind of like the dark UI elements for dialogs and menus, as it feels like it pairs well with the incognito-ness.
