### ISSUE TITLE
Browser button icons are too-big on non-elementary platforms

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/ephemeral#232]
It looks like they're currently always 24, but should be 16 on non-elementary.

https://github.com/cassidyjames/ephemeral/blob/5be06875e9f9792ea1ae5ae27c2873a7103be177/src/Widgets/BrowserButton.vala#L134-L138

**Comment by Exalm** [comment]
Ah, makes sense. Really you should probably use the size property here, i.e. toolbar/menu etc one. Then you set toolbar for elementary, button otherwise.

**Comment by cassidyjames** [comment]
iirc I am explictly setting the icon size due to a bug where Firefox icons would sometimes show up as huge or something (we've seen this in menus in Code, at least). When dealing with app-provided icons I think it was just safer to explicitly set the icon size.
