### ISSUE TITLE
Error using Microsoft Teams

### ISSUE THREAD

**Issue by Peter2121** [cassidyjames/ephemeral#263]
Microsoft Teams is nos usable with Ephemeral:
```
% ephemeral
Fontconfig warning: "/usr/local/etc/fonts/local.conf", line 1093: saw number, expected matrix

** (ephemeral:25269): CRITICAL **: 14:54:08.842: Application.vala:177: Couldn't read /etc/os-release: Error opening file /etc/os-release: No such file or directory

** (ephemeral:25269): CRITICAL **: 14:54:08.847: Application.vala:177: Couldn't read /etc/os-release: Error opening file /etc/os-release: No such file or directory
Fontconfig warning: "/usr/local/etc/fonts/local.conf", line 1093: saw number, expected matrix
Fontconfig warning: "/usr/local/etc/fonts/local.conf", line 1093: saw number, expected matrix
Fontconfig warning: "/usr/local/etc/fonts/local.conf", line 1093: saw number, expected matrix

** (<unknown>:25370): CRITICAL **: 14:56:36.322: gst_gl_context_activate: assertion 'GST_IS_GL_CONTEXT (context)' failed

** (<unknown>:25370): CRITICAL **: 14:56:36.322: gst_gl_context_activate: assertion 'GST_IS_GL_CONTEXT (context)' failed

** (<unknown>:25370): CRITICAL **: 14:56:36.322: gst_gl_context_get_display: assertion 'GST_IS_GL_CONTEXT (context)' failed

** (<unknown>:25370): CRITICAL **: 14:56:36.322: gst_gl_display_get_handle_type: assertion 'GST_IS_GL_DISPLAY (display)' failed
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_mutex_lock': Resource deadlock avoided.  Aborting.

(ephemeral:25269): Gtk-CRITICAL **: 14:56:36.827: gtk_entry_set_text: assertion 'text != NULL' failed

(ephemeral:25269): Gtk-CRITICAL **: 14:56:36.827: gtk_entry_set_text: assertion 'text != NULL' failed
```

OS: FreeBSD 12.1-RELEASE-p8 amd64
Glib: 2.66.0
Gtk: 3.24.20
Vala: 0.48.10

**Comment by janxkoci** [comment]
I don't seem to have any issue there (on elementary OS Hera & Ephemeral), although I don't have any organization registered there so I cannot test in the web app itself. But login with skype account went through fine.

Anyway, can you test it in Epiphany, to see if it's really Ephemeral issue or rather WebkitGTK issue? And what is your Webkit version?

**Comment by Peter2121** [comment]
Thanks for pointing WebKit.
I could solve the problem upgrading webkit2-gtk3: 2.28.4 -> 2.30.1 and rebuilding Ephemeral.
For your information: with Epiphany MS Teams does not work at all (I cannot pass authentication - problem of cookies). I did not search deeper as Epiphany is too heavy and it has too many dependencies, I don't want to have all of them installed on my PC.

**Comment by janxkoci** [comment]
> with Epiphany MS Teams does not work at all (I cannot pass authentication - problem of cookies).

Yes, this is the new Inteligent Tracking Protection (ITP) implemented in WebkitGTK and Epiphany 3.38. I have problems with this too, as I had in Safari in my office some time ago. I'm trying to get them to allow some whitelisting on their [bugzilla](https://bugs.webkit.org/show_bug.cgi?id=216922), you can upvote the issue there if you want.

**Comment by Peter2121** [comment]
If the ITP problem is WebKit-related - how could it work in Ephemeral and don't work in Epiphany using the same WebKit??

**Comment by janxkoci** [comment]
I'm guessing, but I see two options: either it needs to be enabled in the browser too, or possibly it's because of the version - flatpak of Epiphany has webkit 2.30.1, while Ephemeral is still using 2.28, until 2.30 will be backported. From what you said though, I think it's the first case - it needs work in the browser too.

**Comment by Peter2121** [comment]
So, it would be possible to activate/deactivate this option in browser? 
Nice :) 
Note that I built Ephemeral with 2.30.

**Comment by janxkoci** [comment]
I hope this will get implemented, yes.

I noted, that's why I bet on the first option ;)
