### ISSUE TITLE
[Feature request] Add the possibility to disable CSD

### ISSUE THREAD

**Issue by Peter2121** [cassidyjames/ephemeral#264]
When Ephemeral is used on non-GTK DE - il looks strange with client-side decoration (CSD) active by default. Please, add an option to disable it in Ephemeral's settings.

![shot-2020-10-05_11-23-37](https://user-images.githubusercontent.com/3807655/95062428-3cb63a00-06fd-11eb-8d83-5bfdd389f7af.jpg)

**Comment by cassidyjames** [comment]
This is not a matter of just "disabling" something, but would require significantly redesigning the app and maintaining two separate UIs for different platforms; something I am not willing to do personally, considering I maintain Ephemeral alone in my free time for elementary OS.

That said, what is the _specific_ issue you have with the client-side decoration? Is the icon color wrong here? If so, that has nothing to do with CSD and is more likely an issue with either the in-app CSS or the GTK theme your system is using. How do other GNOME/GTK apps look on your system?

**Comment by Peter2121** [comment]
> That said, what is the _specific_ issue you have with the client-side decoration?

- The Ephemeral application looks strange without WM's title.
- The menu shown by WM that should be shown on click inside the windows title does not work (as there is no title).
- The position of window's buttons (minimize/maximize/close) is on the right side and not on the left side.

> How do other GNOME/GTK apps look on your system?

Leferea:
![liferea](https://user-images.githubusercontent.com/3807655/95560389-8367a500-0a19-11eb-89e2-3e3085bc564e.jpg)

Geany:
![geany](https://user-images.githubusercontent.com/3807655/95560414-8cf10d00-0a19-11eb-94c4-0bb628805880.jpg)

Ephemeral (started normally):
![ephemeral-csd](https://user-images.githubusercontent.com/3807655/95560469-a1350a00-0a19-11eb-9fce-425a0ad49dc4.jpg)

Ephemeral (started using gtk3-nocsd):
![ephemeral-nocsd](https://user-images.githubusercontent.com/3807655/95560539-bb6ee800-0a19-11eb-83f9-75fc803a8f77.jpg)

Geany and Liferea are GTK3 applications, started normally. They have a correct look, respecting the current WM that provides windows decorations. To get the same behavior with Ephemeral I use [gtk3-nocsd](https://github.com/PCMan/gtk3-nocsd). I hope you will be able to use the same approach as the one used by gtk3-nocsd developers to disable CSD automatically in non-GNOME WMs (or just add such option in Ephemeral's parameters so the user can choose if he wants CSD or not).

**Comment by cassidyjames** [comment]
As stated in the README, Ephemeral is designed and developed exclusively for elementary OS. If other environments want to do something different with GTK3 apps using headerbars, it's up to those environments to implement something like gtk3-nocsd—for what it's worth, my brief tests of Ephemeral on Manjaro seemed to imply Manjaro is doing that, or their compositor somehow works differently and places a server-side titlebar on top of the Ephemeral window as users of that OS might expect.

I don't have the time or interest to do extra work to support other environments.
