### ISSUE TITLE
HTML5 video doesn't work on Odin

### ISSUE THREAD

**Issue by hanaral** [cassidyjames/ephemeral#267]
Not sure if this is related to Odin or ephemeral, but I haven't seen anyone mention it.

**Comment by cassidyjames** [comment]
It probably just requires installation of codecs.

**Comment by hanaral** [comment]
> It probably just requires installation of codecs.

I know it's not really that relevant here, but could you point me in the right direction for the correct packages?
Also since it's likely a codec thing, I'll close the issue once it's resolved (because I'm pretty sure there is already an open issue on elementary for the codecs not being installed by default)

**Comment by hanaral** [comment]
Fixed by installing `ubuntu-restricted-extras`
