### ISSUE TITLE
Make translatable

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/ephemeral#34]
What it says on the tin. Need to add PO files and make the build system aware of them.

**Comment by NathanBnm** [comment]
I am ready to add the French translation as soon as possible :+1:

**Comment by Vistaus** [comment]
And I'm ready to add the Dutch translation as soon as possible :)

**Comment by hannesschulze** [comment]
I'd add German translations then :)

**Comment by cassidyjames** [comment]
Thanks @NathanBnm, @Vistaus, and @hannesschulze (and anyone else wanting to contribute translations!). This has been merged and is good to go! To translate, see: https://github.com/cassidyjames/ephemeral/tree/master/po#readme
