### ISSUE TITLE
Alert boxes don't follow elementary HIG

### ISSUE THREAD

**Issue by arshubham** [cassidyjames/ephemeral#48]
Demo url: https://www.w3schools.com/js/tryit.asp?filename=tryjs_prompt 
This issue also affects epiphany. There might be a way to override them. If not I would file an upstream issue.

**Comment by cassidyjames** [comment]
![image](https://user-images.githubusercontent.com/611168/51070871-898ede80-1605-11e9-9038-17cf96589cfc.png)

**Comment by davidmhewitt** [comment]
It should be possible to connect to this signal, build the dialog and prevent propagation:
https://valadoc.org/webkit2gtk-4.0/WebKit.WebView.script_dialog.html
