### ISSUE TITLE
Problems with Twitch and YouTube

### ISSUE THREAD

**Issue by djendreizak** [cassidyjames/ephemeral#51]
I can't watch any live streams on Twitch (Error Code 6000) or 1080p videos on YouTube. Missing "Media Source Extensions" and "MSE & WebM VP9".

**Comment by cassidyjames** [comment]
I'm not sure if WebKitGTK in elementary OS supports 1080p on YouTube for similar reasons. I'll investigate and see if there's anything I can do at the browser level, though.

**Comment by cassidyjames** [comment]
It looks like I can enable Media Source Extensions: https://blogs.gnome.org/mcatanzaro/2018/11/02/webkitgtk-2-22-2-and-2-22-3-media-source-extensions-and-youtube/
