### ISSUE TITLE
Add a way to change the default search engine

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [cassidyjames/ephemeral#54]
Currently the search engine is automatically DuckDuckGo, right? I don't know where they have their servers, but maybe it would be nice if it would be possible to add my own search engines and also be able to remove unpopular ones. E.g. Searx (which I can also host myself) or Startpage, which have at least server locations in Europe.

**Comment by NathanBnm** [comment]
@cassidyjames In addition to DuckDuckGo I was thinking to others ethical search engines like:
- Qwant (https://www.qwant.com/)
- Ecosia (https://www.ecosia.org/)
- Lilo (https://search.lilo.org/)

**Comment by cassidyjames** [comment]
@NathanBnm full custom search engine support will be in the next (5.0) release. :smile:

**Comment by NathanBnm** [comment]
Great! :smile:
