### ISSUE TITLE
Window decoration?

### ISSUE THREAD

**Issue by Peter2121** [cassidyjames/ephemeral#58]
I've just compiled ephemeral on FreeBSD 11.1 x64 and I can confirm that it works correctly (besides WebKit bug on FreeBSD [https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229491](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229491), so WEBKIT_DISABLE_COMPOSITING_MODE=1 is needed).
There is a small problem though, not FreeBSD related. 
I use Enlightenment DE with a custom theme - windows title buttons are at the left side. Ephemeral disables the window decoration and put window control buttons on the right side. So the question is - can I restore window decoration, provided by my WM or move Ephemeral-provided buttons on the left side?

**Comment by cassidyjames** [comment]
Ephemeral is a GTK3 app that uses a headerbar and consequently client-side decorations. It should follow the system-wide GTK settings; for example, on elementary OS the close button is on the left and maximize is on the right. There is no special code within Ephemeral itself for this.
