### ISSUE TITLE
Add ephemeral to securitychecklist

### ISSUE THREAD

**Issue by pablopunk** [cassidyjames/ephemeral#70]
[Brian Lovin](https://github.com/brianlovin) (cofounder of Spectrum and designer at Github) released a useful list of tools to enhance user security.

https://securitycheckli.st/

There's a **browser** section, maybe we could add _ephemeral_ there as an option. It accepts PRs:

https://github.com/brianlovin/security-checklist

Or maybe we could wait until major features are addressed (like [blocking trackers](https://github.com/cassidyjames/ephemeral/issues/13))

**Comment by TingPing** [comment]
There are thousands of browsers that exist, I don't think its makes sense to put Ephemeral next to Firefox or Tor which are actually defining privacy on the web while this is just a WebKitGTK wrapper atm.

**Comment by cassidyjames** [comment]
Closing since there's nothing actionable within this codebase.
