### ISSUE TITLE
Pause media playback when opening the site in another browser

### ISSUE THREAD

**Issue by hannesschulze** [cassidyjames/ephemeral#71]
I feel like, if I open for example YouTube in another browser, playback in Ephemeral should automatically be paused.

I don't know if this can be solved in Webkit without running some javascript code.

**Comment by TingPing** [comment]
> I don't know if this can be solved in Webkit without running some javascript code.

You would.

**Comment by cassidyjames** [comment]
@hannesschulze something else I was wondering: should Ephemeral just close when opening a link in another browser? The major issue I see with that is losing your history or any filled-in data, though.

**Comment by cassidyjames** [comment]
@hannesschulze #118 was implemented, would that be sufficient to you? I don't think I want to mess more with the contents of the actual page other than optionally closing the window.

**Comment by hannesschulze** [comment]
Ah, sorry. I completely forgot about this. :smile: I'm personally fine with this solution and I also think that messing with the page content is kinda bad. Thank you!
