### ISSUE TITLE
Zoom gets out of sync with "default" button in new windows

### ISSUE THREAD

**Issue by arshubham** [cassidyjames/ephemeral#79]
Steps:
1. Open a webpage.
2. zoom.
3. start a new session. (either by clicking erase browsing history or open a new window or even closing all windows and reopening)
4. Open another web page.
5. It is still zoomed.  (Zoom button shows 100%)

**Comment by cassidyjames** [comment]
@arshubham the zoom level should be remembered by design (my thinking is that if someone always wants to zoom in, i.e. for accessibility reasons, they can just set and forget. However, if the actual zoom level and the reported level is mismatched, that's a bug!
