### ISSUE TITLE
More detailed information to users what to expect from ephemeral.

### ISSUE THREAD

**Issue by arshubham** [cassidyjames/ephemeral#91]
I last nightly Firefox Added a link to common myths about Private Browsing. 
![image](https://user-images.githubusercontent.com/14235191/51689961-96d99f00-1fef-11e9-9ce6-d735e54fd507.png)
https://support.mozilla.org/en-US/kb/common-myths-about-private-browsing

Maybe ephemeral can incorporate something like this.

**Comment by cassidyjames** [comment]
@arshubham Ephemeral has a similar message on the welcome screen. Those "myths" don't apply cleanly to Ephemeral either, but I don't want to maintain my own website for users. Are there specific instances where you think the welcome message in Ephemeral is inadequate?

**Comment by home-7** [comment]
he talks about auto clear search and browse history when you quit the app !!

**Comment by cassidyjames** [comment]
@home-7 Ephemeral already does that since day one…

**Comment by home-7** [comment]
@cassidyjames thank you for correct me.
and good app.
