### ISSUE TITLE
Support for Tor

### ISSUE THREAD

**Issue by Mondei1** [cassidyjames/ephemeral#98]
I saw this feature in the Brave browser where you have the ability to start a incognito session with Tor. The browser will route every request throw the Tor network which makes you anonymous without buying a good VPN to hide your IP. 

I think this is a pretty good feature to add.

**Comment by TingPing** [comment]
You lose out on all the anti-tracking features by doing that... Sounds like a bad idea.

**Comment by Mondei1** [comment]
@TingPing Why do you lose all of the anti-tracking features? The only thing that changes is you IP address to the public and maybe a lose of loading performance. It should be possible to enable it in the setting or somewhere.

**Comment by TingPing** [comment]
The value of tor-browser is that all users are using identical software, down to the window size and fonts it exposes. That means it is very hard to track users but ephemeral and surely brave completely eliminate that making it very easy to track such a small userbase.

**Comment by Mondei1** [comment]
Mmm... makes sense. Okay, I had not thought about browser fingerprinting. I mean Ephemeral can manipulate such requests and limit the fonts and stuff but I think this is a very unclean approach.
It was just a thought. Then I can close this issue I guess...

**Comment by TingPing** [comment]
>  I mean Ephemeral can manipulate such requests and limit the fonts and stuff but I think this is a very unclean approach.

It would be a lot of work and would never succeed in the end because WebKit and Gecko are very different in what they support and expose making fingerprinting always a possibility.
